export const ADD_TO_CART = 'ADD_TO_CART'
export const CHANGE_MESSAGES = 'CHANGE_MESSAGES'
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART'
export const UPDATE_QUANTITY_PRODUCT_IN_CART = 'UPDATE_QUANTITY_PRODUCT_IN_CART'